-- MySQL Script generated by MySQL Workbench
-- Mon May 24 10:56:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `role` INT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cineplex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cineplex` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cineplex` (
  `idCineplex` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`idCineplex`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`film` ;

CREATE TABLE IF NOT EXISTS `mydb`.`film` (
  `idFilm` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `datePublic` DATE NULL,
  `poster` VARCHAR(45) NULL,
  PRIMARY KEY (`idFilm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cinema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cinema` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cinema` (
  `idCinema` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `idCineplex` INT NULL,
  `type` VARCHAR(45) NULL,
  `width` INT NULL,
  `height` INT NULL,
  PRIMARY KEY (`idCinema`),
  CONSTRAINT `FK_Cinema_Cineplex`
    FOREIGN KEY (`idCinema`)
    REFERENCES `mydb`.`cineplex` (`idCineplex`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`showtime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`showtime` ;

CREATE TABLE IF NOT EXISTS `mydb`.`showtime` (
  `idFilm` INT NOT NULL,
  `idCinema` INT NOT NULL,
  `timeStart` TIME NULL,
  `timeEnd` TIME NULL,
  `prince` INT NULL,
  PRIMARY KEY (`idFilm`, `idCinema`),
  INDEX `FK_ShowTime_idCinema_idx` (`idCinema` ASC) VISIBLE,
  CONSTRAINT `FK_ShowTime_idFilm`
    FOREIGN KEY (`idFilm`)
    REFERENCES `mydb`.`film` (`idFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ShowTime_idCinema`
    FOREIGN KEY (`idCinema`)
    REFERENCES `mydb`.`cinema` (`idCinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`booking` ;

CREATE TABLE IF NOT EXISTS `mydb`.`booking` (
  `idBooking` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NULL,
  `idShowTime` INT NULL,
  `timeBooking` DATETIME NULL,
  `totalPrince` INT NULL,
  PRIMARY KEY (`idBooking`),
  INDEX `FK_Booking_User_idx` (`idUser` ASC) VISIBLE,
  INDEX `FK_Booking_Showtime_idx` (`idShowTime` ASC) VISIBLE,
  CONSTRAINT `FK_Booking_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Booking_Showtime`
    FOREIGN KEY (`idShowTime`)
    REFERENCES `mydb`.`showtime` (`idFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ticket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `idBooking` INT NULL,
  `postion` VARCHAR(45) NULL,
  `widthPos` VARCHAR(45) NULL,
  `heightPos` VARCHAR(45) NULL,
  `prince` INT NULL,
  PRIMARY KEY (`idTicket`),
  INDEX `FK_Ticket_Booking_idx` (`idBooking` ASC) VISIBLE,
  CONSTRAINT `FK_Ticket_Booking`
    FOREIGN KEY (`idBooking`)
    REFERENCES `mydb`.`booking` (`idBooking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
