-- MySQL Script generated by MySQL Workbench
-- Fri May 21 12:33:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cineplex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cineplex` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cineplex` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`film` ;

CREATE TABLE IF NOT EXISTS `mydb`.`film` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `datePublic` DATE NULL,
  `poster` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cinema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cinema` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cinema` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `idCineplex` INT NULL,
  `type` VARCHAR(45) NULL,
  `width` INT NULL,
  `height` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_Cinema_Cineplex`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`cineplex` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`showtime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`showtime` ;

CREATE TABLE IF NOT EXISTS `mydb`.`showtime` (
  `idFilm` INT NOT NULL,
  `idCinema` INT NOT NULL,
  `timeStart` TIME NULL,
  `timeEnd` TIME NULL,
  `prince` INT NULL,
  PRIMARY KEY (`idFilm`, `idCinema`),
  INDEX `FK_ShowTime_idCinema_idx` (`idCinema` ASC) VISIBLE,
  CONSTRAINT `FK_ShowTime_idFilm`
    FOREIGN KEY (`idFilm`)
    REFERENCES `mydb`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ShowTime_idCinema`
    FOREIGN KEY (`idCinema`)
    REFERENCES `mydb`.`cinema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`booking` ;

CREATE TABLE IF NOT EXISTS `mydb`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idusers` INT NULL,
  `idShowTime` INT NULL,
  `timeBooking` DATETIME NULL,
  `totalPrince` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Booking_users_idx` (`idusers` ASC) VISIBLE,
  INDEX `FK_Booking_Showtime_idx` (`idShowTime` ASC) VISIBLE,
  CONSTRAINT `FK_Booking_users`
    FOREIGN KEY (`idusers`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Booking_Showtime`
    FOREIGN KEY (`idShowTime`)
    REFERENCES `mydb`.`showtime` (`idFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ticket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idBooking` INT NULL,
  `postion` VARCHAR(45) NULL,
  `widthPos` VARCHAR(45) NULL,
  `heightPos` VARCHAR(45) NULL,
  `prince` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Ticket_Booking_idx` (`idBooking` ASC) VISIBLE,
  CONSTRAINT `FK_Ticket_Booking`
    FOREIGN KEY (`idBooking`)
    REFERENCES `mydb`.`booking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
